# Generated by Django 5.2.13 on 2026-06-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticproduct',
            name='badges',
            field=models.ManyToManyField(blank=True, to='core.cosmeticbadge'),
        ),
    ]
