# Generated by Django 5.2.13 on 2026-05-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_created_at_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='badge',
        ),
        migrations.AddField(
            model_name='product',
            name='badges',
            field=models.ManyToManyField(blank=True, to='core.badge'),
        ),
    ]
