# Generated by Django 6.1 on 2026-08-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSPViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('document_uri', models.URLField(blank=True, max_length=2000)),
                ('referrer', models.URLField(blank=True, max_length=2000)),
                ('violated_directive', models.CharField(blank=True, db_index=True, max_length=255)),
                ('effective_directive', models.CharField(blank=True, db_index=True, max_length=255)),
                ('original_policy', models.TextField(blank=True)),
                ('blocked_uri', models.CharField(blank=True, db_index=True, max_length=2000)),
                ('source_file', models.CharField(blank=True, max_length=2000)),
                ('line_number', models.IntegerField(default=0)),
                ('column_number', models.IntegerField(default=0)),
                ('status_code', models.IntegerField(default=0)),
                ('script_sample', models.CharField(blank=True, max_length=512)),
                ('disposition', models.CharField(choices=[('enforce', 'Enforce'), ('report', 'Report Only')], default='enforce', max_length=50)),
            ],
            options={
                'verbose_name': 'CSP Violation',
                'verbose_name_plural': 'CSP Violations',
                'db_table': 'csp_violations',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='csp_violati_timesta_0bee75_idx'), models.Index(fields=['effective_directive', '-timestamp'], name='csp_violati_effecti_b6b415_idx'), models.Index(fields=['blocked_uri'], name='csp_violati_blocked_886ef7_idx'), models.Index(fields=['disposition'], name='csp_violati_disposi_751b2c_idx')],
            },
        ),
    ]
